name: CI Pipeline

# This workflow is triggered on pushes and pull requests
on:
  push:

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment (Use a specific Node.js version)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4
      - name: Build project
        run: npm run build


      # Step 5: Upload build artifacts (optional)
      # This is useful if you want to store or use the build in subsequent jobs
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: egor.khaybulov@epitech.eu
          build_dir: dist